name: "Install TimescaleDB"
description: "Builds and installs TimescaleDB"

inputs:
  # TimescaleDB version; if omitted the latest version from the main branch is built
  ts-version:
    required: false
    default: ''
  pg-install-dir:
    required: false
    default: postgresql

runs:
  using: "composite"
  steps:
    - name: Checkout timescaledb
      uses: actions/checkout@v3
      with:
        repository: timescale/timescaledb
        ref: ${{ inputs.ts-version }}
        path: timescaledb

    - name: Build timescaledb
      shell: bash
      env:
        tsdb_build_args: -DTAP_CHECKS=OFF -DWARNINGS_AS_ERRORS=ON
        ##   -DREQUIRE_ALL_TESTS=ON
        CC: gcc
        CXX: g++
      run: |
        cd timescaledb
        ./bootstrap -DCMAKE_BUILD_TYPE=Release -DPG_PATH=${{ inputs.pg-install-dir }} ${tsdb_build_args} -DLINTER_STRICT=ON
        make -j$(nproc) -C build
        make -C build install
