repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ["--all", "--"]
      - id: cargo-check
        args: ["--"]
      - id: clippy
        args: ["--all-targets", "--", "-D", "warnings"]
