repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ["--manifest-path", "pgvectorscale/Cargo.toml", "--"]
      - id: cargo-check
        args: ["--manifest-path", "pgvectorscale/Cargo.toml", "--"]
      - id: clippy
        args: ["--manifest-path", "pgvectorscale/Cargo.toml", "--"]
