name: "Install linux packages"

runs:
  using: "composite"
  steps:
      - name: Install Linux Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y flex bison lcov systemd-coredump gdb libblas-dev libipc-run-perl libtest-most-perl clang-14 llvm-14 llvm-14-dev llvm-14-runtime llvm-14-tools
