/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/

--rename index access method

UPDATE pg_catalog.pg_am SET amname = 'diskann' WHERE amname = 'tsv';
ALTER FUNCTION tsv_amhandler(internal) RENAME TO diskann_amhandler;

-- src/access_method/mod.rs:48
-- pgvectorscale::access_method::amhandler

    CREATE OR REPLACE FUNCTION diskann_amhandler(internal) RETURNS index_am_handler PARALLEL SAFE IMMUTABLE STRICT COST 0.0001 LANGUAGE c AS '$libdir/vectorscale-0.2.0', 'amhandler_wrapper';

    DO $$
    DECLARE
        c int;
    BEGIN
        SELECT count(*)
        INTO c
        FROM pg_catalog.pg_am a
        WHERE a.amname = 'diskann';

        IF c = 0 THEN
            CREATE ACCESS METHOD diskann TYPE INDEX HANDLER diskann_amhandler;
        END IF;
    END;
    $$;




-- src/access_method/mod.rs:91

DO $$
DECLARE
  c int;
BEGIN
    SELECT count(*)
    INTO c
    FROM pg_catalog.pg_opclass c
    WHERE c.opcname = 'vector_cosine_ops'
    AND c.opcmethod = (SELECT oid FROM pg_catalog.pg_am am  WHERE am.amname = 'diskann');

    IF c = 0 THEN
        CREATE OPERATOR CLASS vector_cosine_ops DEFAULT
        FOR TYPE @extschema:vector@.vector USING diskann AS
            OPERATOR 1 @extschema:vector@.<=> (@extschema:vector@.vector, @extschema:vector@.vector) FOR ORDER BY pg_catalog.float_ops;
    END IF;

    -- Refuse wrongly bound DiskANN vector opclasses left behind by older installs.
    IF EXISTS (
        SELECT 1
        FROM pg_catalog.pg_opclass c
        JOIN pg_catalog.pg_am am ON am.oid = c.opcmethod
        WHERE am.amname = 'diskann'
          AND c.opcnamespace = (SELECT oid FROM pg_catalog.pg_namespace WHERE nspname = '@extschema@')
          AND c.opcname IN ('vector_cosine_ops', 'vector_l2_ops', 'vector_ip_ops')
          AND c.opcintype IS DISTINCT FROM '@extschema:vector@.vector'::pg_catalog.regtype
    ) THEN
        RAISE EXCEPTION 'diskann: a vector operator class is not bound to pgvector''s vector type; drop the affected operator class and recreate the extension objects';
    END IF;

END;
$$;
