/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- pgvectorscale/src/access_method/mod.rs:28
-- vectorscale::access_method::amhandler

    CREATE OR REPLACE FUNCTION diskann_amhandler(internal) RETURNS index_am_handler PARALLEL SAFE IMMUTABLE STRICT COST 0.0001 LANGUAGE c AS 'vectorscale-0.9.1', 'amhandler_wrapper';

    DO $$
    DECLARE
        c int;
    BEGIN
        SELECT count(*)
        INTO c
        FROM pg_catalog.pg_am a
        WHERE a.amname = 'diskann';

        IF c = 0 THEN
            CREATE ACCESS METHOD diskann TYPE INDEX HANDLER diskann_amhandler;
        END IF;
    END;
    $$;
/* </end connected objects> */

/* <begin connected objects> */
-- pgvectorscale/src/access_method/distance/mod.rs:52
-- vectorscale::access_method::distance::distance_type_cosine
CREATE OR REPLACE FUNCTION "distance_type_cosine"() RETURNS smallint /* i16 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'vectorscale-0.9.1', 'distance_type_cosine_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pgvectorscale/src/access_method/distance/mod.rs:62
-- vectorscale::access_method::distance::distance_type_inner_product
CREATE OR REPLACE FUNCTION "distance_type_inner_product"() RETURNS smallint /* i16 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'vectorscale-0.9.1', 'distance_type_inner_product_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pgvectorscale/src/access_method/distance/mod.rs:57
-- vectorscale::access_method::distance::distance_type_l2
CREATE OR REPLACE FUNCTION "distance_type_l2"() RETURNS smallint /* i16 */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'vectorscale-0.9.1', 'distance_type_l2_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pgvectorscale/src/access_method/mod.rs:374
-- vectorscale::access_method::smallint_array_overlap
CREATE OR REPLACE FUNCTION "smallint_array_overlap"(
	"left" smallint[], /* pgrx::datum::array::Array<i16> */
	"right" smallint[] /* pgrx::datum::array::Array<i16> */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'vectorscale-0.9.1', 'smallint_array_overlap_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- pgvectorscale/src/access_method/mod.rs:167
-- requires:
--   amhandler
--   distance_type_cosine
--   distance_type_l2
--   distance_type_inner_product
--   smallint_array_overlap


DO $$
DECLARE
  have_cos_ops int;
  have_l2_ops int;
  have_ip_ops int;
  have_label_ops int;
  vector_schema text;
BEGIN
    -- Has cosine operator class been installed previously?
    SELECT count(*)
    INTO have_cos_ops
    FROM pg_catalog.pg_opclass c
    WHERE c.opcname = 'vector_cosine_ops'
    AND c.opcmethod = (SELECT oid FROM pg_catalog.pg_am am WHERE am.amname = 'diskann')
    AND c.opcnamespace = (SELECT oid FROM pg_catalog.pg_namespace where nspname='@extschema@');

    -- Has L2 operator class been installed previously?
    SELECT count(*)
    INTO have_l2_ops
    FROM pg_catalog.pg_opclass c
    WHERE c.opcname = 'vector_l2_ops'
    AND c.opcmethod = (SELECT oid FROM pg_catalog.pg_am am WHERE am.amname = 'diskann')
    AND c.opcnamespace = (SELECT oid FROM pg_catalog.pg_namespace where nspname='@extschema@');

    -- Has inner product operator class been installed previously?
    SELECT count(*)
    INTO have_ip_ops
    FROM pg_catalog.pg_opclass c
    WHERE c.opcname = 'vector_ip_ops'
    AND c.opcmethod = (SELECT oid FROM pg_catalog.pg_am am WHERE am.amname = 'diskann')
    AND c.opcnamespace = (SELECT oid FROM pg_catalog.pg_namespace where nspname='@extschema@');
    
    -- Has label-filtering support been installed previously?
    SELECT count(*)
    INTO have_label_ops
    FROM pg_catalog.pg_opclass c
    WHERE c.opcname = 'vector_smallint_label_ops'
    AND c.opcmethod = (SELECT oid FROM pg_catalog.pg_am am WHERE am.amname = 'diskann')
    AND c.opcnamespace = (SELECT oid FROM pg_catalog.pg_namespace where nspname='@extschema@');

    SELECT n.nspname
    INTO STRICT vector_schema
    FROM pg_catalog.pg_extension e
    JOIN pg_catalog.pg_namespace n ON n.oid = e.extnamespace
    WHERE e.extname = 'vector';

    IF have_cos_ops = 0 THEN
        EXECUTE pg_catalog.format(
            $opclass$
            CREATE OPERATOR CLASS @extschema@.vector_cosine_ops DEFAULT
            FOR TYPE %1$I.vector USING diskann AS
                OPERATOR 1 %1$I.<=> (%1$I.vector, %1$I.vector) FOR ORDER BY pg_catalog.float_ops,
                FUNCTION 1 @extschema@.distance_type_cosine()
            $opclass$,
            vector_schema
        );
    ELSIF have_l2_ops = 0 THEN
        -- Upgrade from 0.4.0 to 0.5.0.  Update cosine opclass to include
        -- the distance_type_cosine function.
        INSERT INTO pg_catalog.pg_amproc (oid, amprocfamily, amproclefttype, amprocrighttype, amprocnum, amproc)
        SELECT  (select (max(oid)::int + 1)::oid from pg_catalog.pg_amproc), c.opcfamily, c.opcintype, c.opcintype, 1, '@extschema@.distance_type_l2'::regproc
        FROM pg_catalog.pg_opclass c, pg_catalog.pg_am a
        WHERE a.oid = c.opcmethod AND c.opcname = 'vector_cosine_ops' AND a.amname = 'diskann';
    END IF;

    IF have_l2_ops = 0 THEN
        EXECUTE pg_catalog.format(
            $opclass$
            CREATE OPERATOR CLASS @extschema@.vector_l2_ops
            FOR TYPE %1$I.vector USING diskann AS
                OPERATOR 1 %1$I.<-> (%1$I.vector, %1$I.vector) FOR ORDER BY pg_catalog.float_ops,
                FUNCTION 1 @extschema@.distance_type_l2()
            $opclass$,
            vector_schema
        );
    END IF;

    IF have_ip_ops = 0 THEN
        EXECUTE pg_catalog.format(
            $opclass$
            CREATE OPERATOR CLASS @extschema@.vector_ip_ops
            FOR TYPE %1$I.vector USING diskann AS
                OPERATOR 1 %1$I.<#> (%1$I.vector, %1$I.vector) FOR ORDER BY pg_catalog.float_ops,
                FUNCTION 1 @extschema@.distance_type_inner_product()
            $opclass$,
            vector_schema
        );
    END IF;
    
    -- First, check if the && operator exists for smallint[] in this extension schema
    IF NOT EXISTS (
        SELECT 1 FROM pg_catalog.pg_operator
        WHERE oprname = '&&'
        AND oprnamespace = '@extschema@'::regnamespace
        AND oprleft = 'smallint[]'::regtype
        AND oprright = 'smallint[]'::regtype
    ) THEN
        -- Create the && operator for smallint[]
        CREATE OPERATOR @extschema@.&& (
            LEFTARG = smallint[],
            RIGHTARG = smallint[],
            PROCEDURE = @extschema@.smallint_array_overlap,
            COMMUTATOR = &&,
            RESTRICT = pg_catalog.contsel,
            JOIN = pg_catalog.contjoinsel
        );
        
        -- Register the operator with the system catalogs for proper selectivity estimation
        -- This is done by adding entries to pg_amop for the array_ops operator class
        ALTER OPERATOR FAMILY pg_catalog.array_ops USING btree
            ADD OPERATOR 3 @extschema@.&& (smallint[], smallint[]) FOR SEARCH;
    END IF;

    IF have_label_ops = 0 THEN
        CREATE OPERATOR CLASS @extschema@.vector_smallint_label_ops
        DEFAULT FOR TYPE smallint[] USING diskann AS
            OPERATOR 1 @extschema@.&&;
    END IF;
END;
$$;

-- Verify the vector opclasses are bound to pgvector's type and operators.  On a
-- fresh install this is trivially true; on an upgrade it rejects opclasses that
-- were captured by a shadow type before the new extension version activates.
DO $$
DECLARE
    expected_vector_type oid;
    vector_namespace oid;
BEGIN
    SELECT t.oid, e.extnamespace
    INTO STRICT expected_vector_type, vector_namespace
    FROM pg_catalog.pg_extension e
    JOIN pg_catalog.pg_type t
      ON t.typnamespace = e.extnamespace
     AND t.typname = 'vector'
    WHERE e.extname = 'vector';

    IF EXISTS (
        SELECT 1
        FROM pg_catalog.pg_opclass c
        JOIN pg_catalog.pg_am am ON am.oid = c.opcmethod
        WHERE am.amname = 'diskann'
          AND c.opcnamespace = '@extschema@'::regnamespace
          AND c.opcname IN (
              'vector_cosine_ops',
              'vector_l2_ops',
              'vector_ip_ops'
          )
          AND (
              c.opcintype IS DISTINCT FROM expected_vector_type
              OR EXISTS (
                  SELECT 1
                  FROM pg_catalog.pg_amop amop
                  JOIN pg_catalog.pg_operator opr ON opr.oid = amop.amopopr
                  WHERE amop.amopfamily = c.opcfamily
                    AND opr.oprnamespace IS DISTINCT FROM vector_namespace
              )
          )
    ) THEN
        RAISE EXCEPTION
            'diskann: a vector operator class is not bound to pgvector''s vector type and operators; drop the affected operator class and recreate the extension objects';
    END IF;
END;
$$;
/* </end connected objects> */

