name: Deb packager
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: ''
      PG:
        description: 'PG major version. Default: 16'
        required: false
        default: '16'
      PG_MIN:
        description: 'PG minor version. Default: 1'
        required: false
        default: '1'
      TAG_GIT_REF:
        description: 'Tag git Ref (leave empty for same as Tag)'
        required: false
        default: ''

jobs:
  packager:
    runs-on: ${{ matrix.runs_on }}

    strategy:
      fail-fast: false
      matrix:
        platform: [ amd64, arm64 ]
        include:
          - platform: amd64
            runs_on: ubuntu-latest
            rustflags: '-C target-feature=+avx2,+fma'
          - platform: arm64
            runs_on: cloud-image-runner-arm64
            rustflags: ''

    env:
      PG_VER: ${{ github.event.inputs.PG }}
      PG_MIN_VER: ${{ github.event.inputs.PG_MIN }}
      PG_SRC_DIR: pgbuild
      PG_INSTALL_DIR: postgresql
      MAKE_JOBS: 6
      PG_CONFIG_PATH: postgresql/bin/pg_config
      TAG: ${{ github.event.inputs.tag }}
      TAG_DIR: pgvectorscale
      TAG_GIT_REF: ${{ github.event.inputs.TAG_GIT_REF == '' && github.event.inputs.tag || github.event.inputs.TAG_GIT_REF}}

    steps:
    - name: Checkout pgvectorscale
      uses: actions/checkout@v4

    - name: Install Linux Packages
      uses: ./.github/actions/install-packages

    - name: Install Deb builder specific packages
      run: |
        sudo apt-get install dpkg-dev debhelper build-essential

    - name: Install PostgreSQL ${{ env.PG_VER }}
      uses: ./.github/actions/install-postgres
      with:
        pg-version: ${{ env.PG_VER }}.${{ env.PG_MIN_VER }}
        pg-src-dir: ~/${{ env.PG_SRC_DIR }}
        pg-install-dir: ~/${{ env.PG_INSTALL_DIR }}

    - name: Checkout ${{ env.TAG }}
      uses: actions/checkout@v4
      with:
        repository: timescale/pgvectorscale
        ref: '${{ env.TAG_GIT_REF }}'
        path: ${{ env.TAG_DIR }}

    - name: Install pgrx
      uses: ./.github/actions/install-pgrx
      with:
        pg-install-dir: ~/${{ env.PG_INSTALL_DIR }}
        pgrx-version: 0.11.1

    - name: Build Deb
      id: debbuild
      run: |
        export PATH=~/${{ env.PG_INSTALL_DIR }}/bin:$PATH
        (cd ${{ env.TAG_DIR }} &&  ${{ matrix.rustflags != '' && format('RUSTFLAGS="{0}"',  matrix.rustflags) || '' }} make package)
        bash scripts/package-deb.sh "${{ env.TAG }}" "${PWD}/${{ env.TAG_DIR }}" "$RUNNER_OS" "${{ env.PG_VER }}"

  # Use a GH artifact, then we can make use of the (quite limited) GH API https://docs.github.com/en/rest/actions/artifacts
  # The artifact will have a TTL of 90 days
    - name: Upload deb as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pgvectorscale-${{ env.TAG }}-pg${{ env.PG_VER }}-${{ matrix.platform }}
        path: pkgdump/pgvectorscale-*${{ env.TAG }}*.deb
